### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by AntonyRileyAtVerto** [tabulate/tabulate#69]
Installation broken under some circumstances with 0.8.4 release.

Seems likely non-ascii included in description.
```
command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c9n59i0n/tabulate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c9n59i0n/tabulate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-c9n59i0n/tabulate/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c9n59i0n/tabulate/setup.py", line 25, in <module>
        f.write(LONG_DESCRIPTION)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 5711-5728: ordinal not in range(128)
    ----------------------------------------
[0m[91mERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[0mThe command '/bin/sh -c pip install --upgrade -r /requirements.txt &&     mkdir /airflow' returned a non-zero code: 1
```

**Comment by AntonyRileyAtVerto** [comment]
Wrong project, sorry.
